/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    ApprovalTimeline: typeof import('./components/common/ApprovalTimeline.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    FileList: typeof import('./components/common/FileList.vue')['default']
    FileUploader: typeof import('./components/common/FileUploader.vue')['default']
    Navbar: typeof import('./components/layout/Navbar.vue')['default']
    RichTextEditor: typeof import('./components/common/RichTextEditor.vue')['default']
    RoleTag: typeof import('./components/common/RoleTag.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarMenu: typeof import('./components/layout/SidebarMenu.vue')['default']
  }
}
